// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

// package:firebase_core/firebase_core.dart 패키지에서 FirebaseOptions만 사용하겠다.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```


// flutter 앱에서 실행 중인 플랫폼에 맞는 Firebase 설정값을 자동으로 골라주는 코드
class DefaultFirebaseOptions {
  // getter
  static FirebaseOptions get currentPlatform {
    // 현재 앱이 실행중이라면...
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbpf69dG7laHDVLjrIw3R-FhOxkDQYDCg',
    appId: '1:912607651198:web:aa57782675167fab0eff2f',
    messagingSenderId: '912607651198',
    projectId: 'captsone-test',
    authDomain: 'captsone-test.firebaseapp.com',
    storageBucket: 'captsone-test.firebasestorage.app',
    measurementId: 'G-K7K7Y904Z6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7Ylo-G8wIxajp5GfhGPqd7dxXZUAxAOc',
    appId: '1:912607651198:android:a6e6f408ed5523980eff2f',
    messagingSenderId: '912607651198',
    projectId: 'captsone-test',
    storageBucket: 'captsone-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz3vN7qkG8F9ThBY2NpD8aWSxQbm7rhag',
    appId: '1:912607651198:ios:4c3c31a33b41d8db0eff2f',
    messagingSenderId: '912607651198',
    projectId: 'captsone-test',
    storageBucket: 'captsone-test.firebasestorage.app',
    iosBundleId: 'com.example.capstone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz3vN7qkG8F9ThBY2NpD8aWSxQbm7rhag',
    appId: '1:912607651198:ios:4c3c31a33b41d8db0eff2f',
    messagingSenderId: '912607651198',
    projectId: 'captsone-test',
    storageBucket: 'captsone-test.firebasestorage.app',
    iosBundleId: 'com.example.capstone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbpf69dG7laHDVLjrIw3R-FhOxkDQYDCg',
    appId: '1:912607651198:web:cddb21542c997b9a0eff2f',
    messagingSenderId: '912607651198',
    projectId: 'captsone-test',
    authDomain: 'captsone-test.firebaseapp.com',
    storageBucket: 'captsone-test.firebasestorage.app',
    measurementId: 'G-BB0HQ5GCXX',
  );
}
